defaults:
  - _self_
  - model: kmops
  - hydra: default.yaml

# run name for logging weights, loss, metrics, and visualizations' using weights and biases
run_name: ???
project_name: "kmops_stereobj"  # Project name for wandb
wandb_online: True
ckpt_path: ""  # if want to resume training from a specific checkpoint

# Training configurations
num_k: 8
aux_loss: True  # whether to use auxiliary loss for each decoder
gpu: 0  # 0
batch_size: 16
num_workers: 8  # Number of workers for data loading

# Hyperparameters
num_epochs: 12
learning_rate: 1e-4
backbone_learning_rate: 1e-5
weight_decay: 1e-4
scheduler:  # MultiStepLR
  milestones:
  - 9
  gamma: 0.1

# One-to-One Matcher relative weight
o2o_coef_class: 2.0  # Class confidence coefficient
o2o_coef_kpts: 8.0   # Keypoints difference coefficient
o2o_coef_oks: 4.0    # OKS-based coefficient
o2o_coef_conf: 1.0

# Loss coefficients
ce_loss_coef: 1.0
kpts_loss_coef: 8.0
oks_loss_coef: 4.0
conf_loss_coef: 1.0

dataset:
  train_pkl: "data/stereobj_train.pkl"
  val_pkl: "data/stereobj_val.pkl"
  names:
    0: blade_razor
    1: hammer
    2: needle_nose_pliers
    3: screwdriver
    4: side_cutters
    5: tape_measure
    6: wire_stripper
    7: wrench
    8: centrifuge_tube
    9: microplate
    10: tube_rack
    11: pipette
    12: sterile_tip_rack

augments:
  flip: 0.5
  random_size_crop: [0.6, 1]
  scale_jitter: [0.6, 1.1]
  resize: [640, 640]  # [w, h]
